package com.weeklycommit.domain.enums;

public enum CarryForwardReason {
	BLOCKED_BY_DEPENDENCY, SCOPE_EXPANDED, REPRIORITIZED, RESOURCE_UNAVAILABLE, TECHNICAL_OBSTACLE, EXTERNAL_DELAY, UNDERESTIMATED, STILL_IN_PROGRESS
}
